<link rel="stylesheet" href="{{ asset('dist/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/font-awesome.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/bootstrap-datepicker.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/bootstrap-timepicker.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/bootstrap-tagsinput.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/duotone-dark.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/iziToast.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/fontawesome-iconpicker.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/bootstrap4-toggle.min.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/summernote-bs4.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/style.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/components.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/spacing.css') }}">
<link rel="stylesheet" href="{{ asset('dist/css/custom.css') }}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous"/>